src/MyProject.Admin/Controllers/GrantController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Dtos.Grant;
using Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Services.Interfaces;
using MyProject.Admin.ExceptionHandling;
using MyProject.Admin.Helpers;
using MyProject.Admin.Configuration.Constants;

namespace MyProject.Admin.Controllers
{
    [Authorize(Policy = AuthorizationConsts.AdministrationPolicy)]
    [TypeFilter(typeof(ControllerExceptionFilterAttribute))]
    public class GrantController : BaseController
    {
        private readonly IPersistedGrantAspNetIdentityService _persistedGrantService;
        private readonly IStringLocalizer<GrantController> _localizer;

        public GrantController(IPersistedGrantAspNetIdentityService persistedGrantService,
            ILogger<ConfigurationController> logger,
            IStringLocalizer<GrantController> localizer) : base(logger)
        {
            _persistedGrantService = persistedGrantService;
            _localizer = localizer;
        }

        [HttpGet]
        public async Task<IActionResult> PersistedGrants(int? page, string search)
        {
            ViewBag.Search = search;
            var persistedGrants = await _persistedGrantService.GetPersistedGrantsByUsersAsync(search, page ?? 1);

            return View(persistedGrants);
        }

        [HttpGet]
        public async Task<IActionResult> PersistedGrantDelete(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var grant = await _persistedGrantService.GetPersistedGrantAsync(UrlHelpers.QueryStringUnSafeHash(id));
            if (grant == null) return NotFound();

            return View(grant);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PersistedGrantDelete(PersistedGrantDto grant)
        {
            await _persistedGrantService.DeletePersistedGrantAsync(grant.Key);

            SuccessNotification(_localizer["SuccessPersistedGrantDelete"], _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(PersistedGrants));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PersistedGrantsDelete(PersistedGrantsDto grants)
        {
            await _persistedGrantService.DeletePersistedGrantsAsync(grants.SubjectId);

            SuccessNotification(_localizer["SuccessPersistedGrantsDelete"], _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(PersistedGrants));
        }


        [HttpGet]
        public async Task<IActionResult> PersistedGrant(string id, int? page)
        {
            var persistedGrants = await _persistedGrantService.GetPersistedGrantsByUserAsync(id, page ?? 1);
            persistedGrants.SubjectId = id;

            return View(persistedGrants);
        }
    }
}

src/MyProject.Admin/Views/Grant/PersistedGrant.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Dtos.Grant
@using MyProject.Admin.Helpers
@using Skoruba.IdentityServer4.Admin.BusinessLogic.Shared.Dtos.Common
@model PersistedGrantsDto
@inject IViewLocalizer Localizer

@{
	ViewBag.Title = Localizer["PageTitle"];
	Layout = "_Layout";
}

<div class="row">
	<div class="col-12">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a asp-controller="Grant" asp-action="PersistedGrants">@Localizer["NavigationPersistedGrants"]</a></li>
				<li class="breadcrumb-item active" aria-current="page">@Model.SubjectId</li>
			</ol>
		</nav>
	</div>

	<div class="col-12">
		<h2>@Localizer["PageTitle"]</h2>
	</div>
</div>

<form id="client-form" asp-controller="Grant" asp-action="PersistedGrantsDelete" Method="post">

	<a href="#" class="btn btn-danger mb-3" data-toggle="modal" data-target="#deletePersistedGrantsModal">@Localizer["ButtonDeleteAll"]</a>

	<!--Hidden -->
	<input type="hidden" asp-for="SubjectId" />

	<div class="row table-responsive">
		<div class="col-12">
			<table class="table table-striped">
				<thead>
                    <tr>
                        <th></th>
                        <th>@Localizer["TableSubjectId"]</th>
                        <th>@Localizer["TableType"]</th>
                        <th>@Localizer["TableExpiration"]</th>
                        <th>@Localizer["TableData"]</th>
                        <th>@Localizer["TableClient"]</th>
                    </tr>
				</thead>

				<tbody>
					@foreach (var persistedGrant in Model.PersistedGrants)
					{
                    <tr>
                        <td><a class="btn btn-danger" asp-action="PersistedGrantDelete" asp-route-id="@UrlHelpers.QueryStringSafeHash(persistedGrant.Key)"><span class="oi oi-x"></span></a></td>
                        <td>@persistedGrant.SubjectId</td>
                        <td>@persistedGrant.Type</td>
                        <td>@persistedGrant.Expiration</td>
                        <td>@persistedGrant.Data</td>
                        <td>@persistedGrant.ClientId</td>
                    </tr>
					}
				</tbody>
			</table>
		</div>
	</div>

	<div class="row">
		<div class="col-12">
			@await Html.PartialAsync("Common/Pager", new Pager { Action = "PersistedGrant", PageSize = Model.PageSize, TotalCount = Model.TotalCount })
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="deletePersistedGrantsModal" tabindex="-1" role="dialog" aria-labelledby="deletePersistedGrantsModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="deletePersistedGrantsModalLabel">@Localizer["DeleteDialogTitle"]</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				</div>
				<div class="modal-body">
					@Localizer["DeleteDialogMessage"]
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-danger">@Localizer["DeleteDialogYes"]</button>
					<button type="button" class="btn btn-outline-primary" data-dismiss="modal">@Localizer["DeleteDialogNo"]</button>
				</div>
			</div>
		</div>
	</div>
</form>

src/MyProject.Admin/Views/Grant/PersistedGrantDelete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Dtos.Grant
@model PersistedGrantDto
@inject IViewLocalizer Localizer

@{
	ViewBag.Title = Localizer["PageTitle"];
	Layout = "_Layout";
}	

<div class="row">
	<div class="col-12">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a asp-controller="Grant" asp-action="PersistedGrants">@Localizer["NavigationPersistedGrants"]</a></li>
				<li class="breadcrumb-item"><a asp-controller="Grant" asp-action="PersistedGrant" asp-route-id="@Model.SubjectId">@Model.SubjectId</a></li>
				<li class="breadcrumb-item active" aria-current="page">@Localizer["PageTitle"]</li>
			</ol>
		</nav>
	</div>

	<div class="col-12">
		<h2>@Localizer["PageTitle"]</h2>
	</div>
</div>

<form id="client-form" asp-controller="Grant" asp-action="PersistedGrantDelete" Method="post">

	<input type="hidden" asp-for="Key" />

	<div class="row table-responsive">
		<div class="col-12">
			<table class="table table-striped">
				<thead>
				<tr>
					<th>@Localizer["TableSubjectId"]</th>
					<th>@Localizer["TableType"]</th>
					<th>@Localizer["TableExpiration"]</th>
					<th>@Localizer["TableData"]</th>
					<th>@Localizer["TableClient"]</th>
				</tr>
				</thead>

				<tbody>
				<tr>
					<td>@Model.SubjectId</td>
					<td>@Model.Type</td>
					<td>@Model.Expiration</td>
					<td>@Model.Data</td>
					<td>@Model.ClientId</td>
				</tr>
				</tbody>
			</table>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<button type="submit" class="btn btn-danger">@Localizer["ButtonDeleteGrant"]</button>
		</div>
	</div>
</form>

src/MyProject.Admin/Views/Grant/PersistedGrants.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Dtos.Grant
@using Skoruba.IdentityServer4.Admin.BusinessLogic.Shared.Dtos.Common
@model PersistedGrantsDto
@inject IViewLocalizer Localizer

@{
	ViewBag.Title = Localizer["PageTitle"];
	Layout = "_Layout";
}

<div class="row">
	<div class="col-12 mb-3">
		<h2>@Localizer["PageTitle"]</h2>
	</div>
</div>

<div class="row">
	<div class="col-12 mb-3">
		@await Html.PartialAsync("Common/Search", new Search { Action = "PersistedGrants", Controller = "Grant" })
	</div>
</div>

<div class="row table-responsive">
	<div class="col-12">
		<table class="table table-striped">
			<thead>
				<tr>
					<th></th>
					<th>@Localizer["TableSubjectId"]</th>
					<th>@Localizer["TableSubjectName"]</th>
				</tr>
			</thead>

			<tbody>
				@foreach (var persistedGrant in Model.PersistedGrants)
				{
					<tr>
						<th scope="row"><a class="btn btn-primary" asp-action="PersistedGrant" asp-route-id="@persistedGrant.SubjectId">@Localizer["TableButtonDetail"]</a></th>
						<td>@persistedGrant.SubjectId</td>
						<td>@persistedGrant.SubjectName</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

<div class="row">
	<div class="col-12">
		@await Html.PartialAsync("Common/Pager", new Pager() { Action = "PersistedGrants", PageSize = Model.PageSize, TotalCount = Model.TotalCount })
	</div>
</div>